config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'home#show'

  resources :rooms, only: %i[index show create], param: :title
  resources :messages, only: :create
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :body, presence: true

  scope :sorted, -> { order(:id) }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { sorted }, dependent: :destroy
  validates :title, presence: true

  after_create_commit { broadcast_append_to "rooms" }

  scope :public_rooms, -> { where(is_private: false) }

  def self.fetch_private_room(room_title, user)
    Room.where(title: room_title, is_private: true).first || user.rooms.create!(title: room_title, is_private: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  DEFAULT_PASSWORD = ENV['DEFAULT_PASSWORD'] || 'Example123456_'
  after_create_commit { broadcast_append_to "users" }

  has_many :rooms, dependent: :destroy
  has_many :messages

  scope :all_except, -> (user_id) { where.not(id: user_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_auth_user, unless: :devise_controller?
  rescue_from ActiveRecord::NotNullViolation, with: :render_invalid_error
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  private

  def check_auth_user
    redirect_to root_path unless user_signed_in?
  end

  def render_invalid_error
    flash[:error] = 'Не заполнены необходимые поля'
    redirect_to root_path
  end

  def render_not_found
    flash[:error] = 'Запись не найдена'
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_auth_user

  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @new_message = current_user.messages.create!(message_params)

    room = @new_message.room
    @new_message.broadcast_append_to room, target: "room_#{room.id}_messages", locals: { message: @new_message }
  end

  private

  def message_params
    params.require(:message).permit(:body, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    @new_room = Room.new
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = @room.messages
    @new_message = current_user.messages.build
  end

  def create
    @new_room = current_user.rooms.create!(title: room_params[:title])
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
 
    @room = Room.fetch_private_room(fetch_room_title(@user, current_user), current_user)
    @messages = @room.messages
    @new_message = current_user.messages.build
  end

  private

  def fetch_room_title(u1, u2)
    users = [u1,u2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<div class="b-example-divider"></div>

    <div class="container">
      <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
          <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
            Главная
          </a>
        </div>

        <% if user_signed_in? %>
          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li class="nav-link px-2 link-secondary"><%= current_user.email%></li>
            <li><%= link_to "Чаты", rooms_path, class: "nav-link px-2"%></li>
          </ul>
        <% end %>
        <div class="col-md-3 text-end">
          <% if user_signed_in? %>
            <%= link_to "Выйти", destroy_user_session_path, data: { "turbo-method": :delete }, class: "btn btn-outline-primary me-2"%>
          <% else %>
            <%= link_to "Логин", new_user_session_path, class: "btn btn-outline-primary me-2"%>
            <%= link_to "Регистрация", new_user_registration_path, class: "btn btn-primary"%>
          <% end %>
        </div>
      </header>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineChatBootstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/messages/_chat_form.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-4">
        <div class="card" id="chat-container" style="border-radius: 15px;">
          <div
            class="card-header d-flex justify-content-between align-items-center p-3 bg-info text-white border-bottom-0"
            style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
            <i class="fas fa-angle-left"></i>
            <p class="mb-0 fw-bold"><%= @room.title %></p>
            <i class="fas fa-times"></i>
          </div>
          <div class="card-body">
            <div id="room_<%= @room.id %>_messages">
              <%= render partial: "messages/message", collection: @messages %>
            </div>

            <%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
              <div class="form-outline">
                <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "form-control" %>
                <%= f.hidden_field :room_id, value: @room.id %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/messages/_message.html.erb
<div class="d-flex flex-row justify-content-start mb-4">
  <div><%= message.user.email %></div>
  <div class="p-3 ms-3" style="border-radius: 15px; background-color: rgba(57, 192, 237,.2);">
    <p class="small mb-0"><%= message.body %></p>
    <span class="badge bg-secondary-subtle text-secondary-emphasis rounded-pill"><%= l(message.created_at, format: :short) %></span>
  </div>
</div>

app/views/rooms/_room.html.erb
<div> <%= link_to room.title, room_path(room.title) %> </div>

app/views/rooms/index.html.erb
<div class="container">
  <h4>Пользователи</h4>
  <%= turbo_stream_from "users" %>
  <div id="users">
    <%= render @users %>
  </div>

  <h4>Комнаты</h4>
  <%= turbo_stream_from "rooms" %>
  <div id="rooms">
    <%= render @rooms %>
  </div>

  <%= form_with(model: @new_room, remote: true, class:'d-flex', data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" }) do |f| %>
  <%= f.text_field :title, class: 'form-control', autocomplete: 'off' %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-4">
        <div class="card" id="chat-container" style="border-radius: 15px;">
          <div
            class="card-header d-flex justify-content-between align-items-center p-3 bg-info text-white border-bottom-0"
            style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
            <i class="fas fa-angle-left"></i>
            <p class="mb-0 fw-bold"><%= @room.title %></p>
            <i class="fas fa-times"></i>
          </div>
          <div class="card-body">
            <div id="room_<%= @room.id %>_messages">
              <%= render partial: "messages/message", collection: @messages %>
            </div>

            <%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
              <div class="form-outline">
                <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "form-control" %>
                <%= f.hidden_field :room_id, value: @room.id %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flash.html.erb
<div class="flash-messages">
  <% flash.each do |type, message| %>
    <div class="flash-message">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div> <%= link_to user.email, user_path(user) %> </div>

app/views/users/show.html.erb
<%= turbo_stream_from @room %>

<%= render 'messages/chat_form' %>